<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-12-15 16:01
=======
# Generated by Django 5.2.8 on 2025-12-16 03:08
>>>>>>> origin/pagina-post

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comentarios', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='post.articulo'),
        ),
    ]
