<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-12-15 16:01
=======
# Generated by Django 5.2.8 on 2025-12-16 03:08
>>>>>>> origin/pagina-post

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_articulos', to=settings.AUTH_USER_MODEL),
        ),
    ]
