# Generated by Django 5.2.8 on 2025-12-06 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_articulo_contenido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_articulos', to=settings.AUTH_USER_MODEL),
        ),
    ]
