# Generated by Django 5.2.8 on 2025-12-17 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
        ('post', '0003_alter_articulo_likes'),
    ]

    operations = [
    ]
